version: '3.8'

services:
  ubuntu:
    build:
      context: ../../
      dockerfile: dockers/ubuntu/Dockerfile
    image: test_ubuntu
    privileged: true
    network_mode: "host"
    volumes:
      - ../../app:/app
      - ../../dockers/docker.py:/app/docker.py
    cap_add:
      - NET_ADMIN
    container_name: ubuntu
    environment:
      mode: ""
      start: ""
    command: ["python3", "docker.py", "${MODE}", "${START}"]