version: '3.8'

services:
  ubuntu:
    build:
      context: ..\..\
      dockerfile: dockers\ubuntu_client\Dockerfile
    image: ubuntu_client
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
      - "0.0.0.0:5555:5555"
    container_name: ubuntu_client
    command: ["python3", "docker.py"]
