version: '3.8'

services:
  ubuntu_client:
    build:
      context: ..\..\
      dockerfile: dockers\fedora38_client\Dockerfile
    image: fedora38_client
    privileged: true
    cap_add:
      - NET_ADMIN
    container_name: fedora38_client
    command: ["python3", "docker.py"]
