FROM fedora:38 AS builder

RUN dnf -y update && dnf -y install gcc-c++ make cmake git wget pkgconfig libnl3-devel nftables-devel boost-devel sudo curl iproute jq

RUN dnf install -y python3 pip && pip install requests

WORKDIR /app

RUN git clone https://github.com/ivankirsanov9062/FlowForge.git -b main .

COPY /dockers/docker.py /app/docker.py

CMD [ "python3", "docker.py" ]